Box.create!([
  {barcode: "LNPS00237", weight: 200.0, height: 39.0, width: 51.0, depth: 21.0, box_number: 17, photo: "0_klj477aq", notes: "Box for TV's", location_id: nil, condition_id: nil},
  {barcode: "LNPS00241", weight: nil, height: 27.0, width: 45.0, depth: 22.0, box_number: 2, photo: "0_ngxsp47i", notes: "UPS's, Microphones, Mic Receivers, Mic Antenas", location_id: nil, condition_id: nil},
  {barcode: "LNPS00242", weight: nil, height: 44.0, width: 59.0, depth: 15.0, box_number: 7, photo: "0_3o836boe", notes: "TV stands box", location_id: nil, condition_id: nil},
  {barcode: "LNPS00245", weight: nil, height: 24.0, width: 18.0, depth: 14.0, box_number: 1, photo: "0_sfazeyoo", notes: "Radios and toolbox", location_id: nil, condition_id: nil},
  {barcode: "LNPS00211", weight: nil, height: 30.0, width: 15.0, depth: 21.0, box_number: 31, photo: "0_213tmvvx", notes: "Laptops and peripherals", location_id: nil, condition_id: nil},
  {barcode: "LNPS00210", weight: nil, height: 30.0, width: 44.0, depth: 28.0, box_number: 6, photo: "0_x0ufywkd", notes: "All kind of cables", location_id: nil, condition_id: nil},
  {barcode: "LNPS00226", weight: nil, height: 32.0, width: 27.0, depth: 17.0, box_number: 4, photo: "0_7yzfg3kb", notes: "ATEM Panel, LED lights, tallys and iKan", location_id: nil, condition_id: nil},
  {barcode: "LNPS00231", weight: nil, height: 25.0, width: 24.0, depth: 15.0, box_number: 19, photo: "0_z2oaj4lk", notes: "MacPro G5 case without wheels", location_id: nil, condition_id: nil},
  {barcode: "LNPS00233", weight: nil, height: 30.0, width: 21.0, depth: 15.0, box_number: 18, photo: "0_xhkyn7l1", notes: "Laptops", location_id: nil, condition_id: nil},
  {barcode: "LNPS00392", weight: nil, height: 19.0, width: 29.0, depth: 15.0, box_number: 88, photo: "0_vux10p0v", notes: "Speaker", location_id: nil, condition_id: nil},
  {barcode: "LNPS00394", weight: nil, height: 24.0, width: 23.0, depth: 12.0, box_number: 58, photo: "0_iboo42bn", notes: "Tricaster", location_id: nil, condition_id: nil},
  {barcode: "LNPS00395", weight: nil, height: 27.0, width: 23.0, depth: 12.0, box_number: 37, photo: "0_0g6levmx", notes: "MacPro Portuguese", location_id: nil, condition_id: nil},
  {barcode: "LNPS00396", weight: nil, height: 25.0, width: 31.0, depth: 12.0, box_number: 35, photo: "0_o8mkjvgr", notes: "MacPro English", location_id: nil, condition_id: nil},
  {barcode: "LNPS00397", weight: nil, height: 26.0, width: 24.0, depth: 12.0, box_number: 36, photo: "0_9tzts0pk", notes: "MacPro caspar", location_id: nil, condition_id: nil},
  {barcode: "LNPS00402", weight: nil, height: 25.0, width: 45.0, depth: 35.0, box_number: 34, photo: "0_0jncazsm", notes: "", location_id: nil, condition_id: nil},
  {barcode: "LNPS00413", weight: nil, height: 31.0, width: 20.0, depth: 27.0, box_number: 32, photo: "0_e9ggglh4", notes: "Main production rack", location_id: nil, condition_id: nil},
  {barcode: "LNPS00415", weight: nil, height: 26.0, width: 21.0, depth: 25.0, box_number: 33, photo: "0_vr9btggw", notes: "Backup rack", location_id: nil, condition_id: nil},
  {barcode: "LNPS00416", weight: nil, height: nil, width: nil, depth: nil, box_number: 48, photo: "0_88fis3rv", notes: "Cables", location_id: nil, condition_id: nil},
  {barcode: "LNPS00419", weight: nil, height: nil, width: nil, depth: nil, box_number: 96, photo: "0_0tqxhijl", notes: "Adapters, mini mixers, ethernet switchers, etc", location_id: nil, condition_id: nil},
  {barcode: "LNPS00425", weight: nil, height: 17.0, width: 32.0, depth: 27.0, box_number: 11, photo: "0_ya5bcsmf", notes: "Audio mixer and small speaker", location_id: nil, condition_id: nil},
  {barcode: "LNPS00428", weight: nil, height: nil, width: nil, depth: nil, box_number: 79, photo: nil, notes: "New rack for specialties", location_id: nil, condition_id: nil},
  {barcode: "LNPS00431", weight: 50.0, height: 15.0, width: 25.0, depth: 25.0, box_number: 12, photo: "0_x5qta9dq", notes: "Intercoms", location_id: nil, condition_id: nil}
])
Category.create!([
  {name: "Audio", description: ""},
  {name: "Video", description: ""},
  {name: "Transmission", description: ""},
  {name: "Power", description: ""},
  {name: "Communications", description: ""},
  {name: "TV's and Monitors", description: ""},
  {name: "Tools", description: ""},
  {name: "Computers", description: "Laptops and desktops"}
])
Item.create!([
  {barcode: "LNPS00236", box_id: 2, product_id: 1, serial_number: "SN01162254", model_number: "U12-42367", price: nil, firmware: "", photo: "0_d9nfsh3x", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00238", box_id: 1, product_id: 2, serial_number: "Z30Z3CB101760Z", model_number: "UN46D7000LFXZA", price: nil, firmware: "", photo: "0_qazfcovt", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00239", box_id: 1, product_id: 3, serial_number: "Z4NS3CFC302786H", model_number: "UN40EH5000FXZA", price: nil, firmware: "", photo: "0_awtrhho0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "lnps00240", box_id: 1, product_id: 3, serial_number: "z4ns3cfc303260p", model_number: "UN40EH5000FXZA", price: nil, firmware: "", photo: "0_0tmpnoek", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00243", box_id: 2, product_id: 1, serial_number: "SN01162196", model_number: "U12-42367", price: nil, firmware: "", photo: "0_yq1tlil9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00194", box_id: 2, product_id: 1, serial_number: "SN01162432", model_number: "U12-42367", price: nil, firmware: "", photo: "0_9la2ntyn", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00235", box_id: 2, product_id: 4, serial_number: "CPKBY2020497", model_number: "CP1350AVRLCD", price: nil, firmware: "", photo: "0_cwz6d6b9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00244", box_id: 2, product_id: 4, serial_number: "CPKCP2000953", model_number: "CP1350AVRLCD", price: nil, firmware: "", photo: "0_9fpqpbdu", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00184", box_id: 21, product_id: 5, serial_number: "3B1310X10091", model_number: "BN1080G", price: nil, firmware: "", photo: "0_q7wq2dt9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00187", box_id: 2, product_id: 6, serial_number: "S1103219A0I", model_number: "X1222USB", price: nil, firmware: "", photo: "0_p0irqykq", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00246", box_id: 4, product_id: 7, serial_number: "B2100485", model_number: "TK-3230", price: nil, firmware: "", photo: "0_ahqsjrps", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00247", box_id: 4, product_id: 7, serial_number: "B1A01334", model_number: "TK-3230", price: nil, firmware: "", photo: "0_ex8v065n", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00220", box_id: 4, product_id: 7, serial_number: "B1A01333", model_number: "TK-3230", price: nil, firmware: "", photo: "0_5n1cmxzy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00219", box_id: 4, product_id: 7, serial_number: "B2100484", model_number: "TK-3230", price: nil, firmware: "", photo: "0_24cfi0ci", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00218", box_id: 4, product_id: 7, serial_number: "B2100482", model_number: "TK-3230", price: nil, firmware: "", photo: "0_ygypn37i", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00217", box_id: 4, product_id: 7, serial_number: "B2100481", model_number: "TK-3230", price: nil, firmware: "", photo: "0_unp34fnw", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00216", box_id: 4, product_id: 7, serial_number: "B1A01348", model_number: "TK-3230", price: nil, firmware: "", photo: "0_2rxo7va4", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00215", box_id: 4, product_id: 7, serial_number: "B1A01346", model_number: "TK-3230", price: nil, firmware: "", photo: "0_7ua1karj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00214", box_id: 4, product_id: 7, serial_number: "B1A01335", model_number: "TK-3230", price: nil, firmware: "", photo: "0_ylpjgkjq", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00213", box_id: 4, product_id: 7, serial_number: "B1A01347", model_number: "TK-3230", price: nil, firmware: "", photo: "0_vtbje9nf", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00212", box_id: 4, product_id: 8, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_nmhmsxka", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00199", box_id: 5, product_id: 9, serial_number: "C02K273UDV33", model_number: "A1286", price: nil, firmware: "OSX Mavericks", photo: "0_pm18q2xr", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00011", box_id: 5, product_id: 9, serial_number: "C02JD0W7F1G3", model_number: "A1286", price: nil, firmware: "OSX Mavericks", photo: "0_7nj9691i", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00198", box_id: 21, product_id: 9, serial_number: "C02K274ADV33", model_number: "A1286", price: nil, firmware: "OSX Mavericks", photo: "0_bcujdbh0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00013", box_id: 5, product_id: 9, serial_number: "C02H20XXDV7N", model_number: "A1286", price: nil, firmware: "OSX Mavericks", photo: "0_l5we45uy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00344", box_id: 5, product_id: 10, serial_number: "1537953", model_number: "", price: nil, firmware: "", photo: "0_zj44haqr", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00209", box_id: 5, product_id: 10, serial_number: "2111789", model_number: "", price: nil, firmware: "", photo: "0_l758xxos", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00357", box_id: 5, product_id: 10, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_4e6e5vg0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00006", box_id: 5, product_id: 9, serial_number: "C02HGZ9DDV13", model_number: "A1278", price: nil, firmware: "OSX Mavericks", photo: "0_8oy7m7yj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00028", box_id: 5, product_id: 11, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_cnp54k9b", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00223", box_id: 5, product_id: 9, serial_number: "C1MJT4PRDTY3", model_number: "A1278", price: nil, firmware: "", photo: "0_8onxrrg6", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00159", box_id: 5, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_nz4foncj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00202", box_id: 5, product_id: 9, serial_number: "C1MJPPTKDTY3", model_number: "A1278", price: nil, firmware: "", photo: "0_bw673vgy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "lnps00222", box_id: 5, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_iqqy9zk2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00022", box_id: 5, product_id: 13, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_0oakc2yt", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00224", box_id: 5, product_id: 14, serial_number: "S1457472A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_qzqdik3s", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00225", box_id: 5, product_id: 14, serial_number: "S1450329A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_g1wu4p1o", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00183", box_id: 5, product_id: 13, serial_number: "CND917037R", model_number: "2530p", price: nil, firmware: "", photo: "0_1fzg4t8t", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00105", box_id: 7, product_id: 15, serial_number: "B207M054", model_number: "MR7", price: nil, firmware: "", photo: "0_s2boso06", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00034", box_id: 7, product_id: 16, serial_number: "845234", model_number: "", price: nil, firmware: "", photo: "0_apiycnc7", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00327", box_id: 7, product_id: 17, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_08fi5fqm", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00227", box_id: 7, product_id: 18, serial_number: "", model_number: "Microbeam 1024", price: nil, firmware: "", photo: "0_j44beday", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00228", box_id: 7, product_id: 18, serial_number: "", model_number: "Microbeam 1024", price: nil, firmware: "", photo: "0_ik9271d8", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00229", box_id: 7, product_id: 18, serial_number: "", model_number: "Microbeam 512", price: nil, firmware: "", photo: "0_6wtz73mo", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00230", box_id: 7, product_id: 18, serial_number: "", model_number: "Microbeam 512", price: nil, firmware: "", photo: "0_62io4j71", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00232", box_id: 8, product_id: 19, serial_number: "SL1E14044849", model_number: "16.4.2 AI", price: nil, firmware: "", photo: "0_uu1lsqc2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00331", box_id: 5, product_id: 13, serial_number: "CND113FTV5", model_number: "2540P", price: nil, firmware: "", photo: "0_9kxp1lcd", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00326", box_id: 9, product_id: 9, serial_number: "C02P502PG3QQ", model_number: "A1502", price: nil, firmware: "", photo: "0_b038e8gy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00345", box_id: 9, product_id: 10, serial_number: "136757", model_number: "", price: nil, firmware: "", photo: "0_qz1zrm5r", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00356", box_id: 9, product_id: 12, serial_number: "1575968", model_number: "", price: nil, firmware: "", photo: "0_ejbdl456", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00170", box_id: 9, product_id: 14, serial_number: "S1049791A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_fhqgo1td", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00353", box_id: 9, product_id: 9, serial_number: "C02MW1J9FH04", model_number: "A1502", price: nil, firmware: "OSX Mavericks", photo: "0_oro2gsfe", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "lnps00234", box_id: 9, product_id: 14, serial_number: "s1450322a31", model_number: "UCA202", price: nil, firmware: "", photo: "0_ag9lyb8d", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00161", box_id: 9, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_wtxvmlut", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00200", box_id: 9, product_id: 9, serial_number: "C1MK3235DV30", model_number: "A1278", price: nil, firmware: "", photo: "0_vag0ll9a", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00169", box_id: 9, product_id: 14, serial_number: "S1116263A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_eqvccx92", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00160", box_id: 9, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_02mp9ikw", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00025", box_id: 9, product_id: 9, serial_number: "C02CQ1NKDC7C", model_number: "A1297", price: nil, firmware: "", photo: "0_y4yu5nom", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00391", box_id: 9, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_vgmbqvco", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00007", box_id: 9, product_id: 9, serial_number: "C0HN0HMDV7P", model_number: "A1286", price: nil, firmware: "", photo: "0_2axkrw7h", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00163", box_id: 9, product_id: 10, serial_number: "1367480", model_number: "", price: nil, firmware: "", photo: "0_kbuusylj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00182", box_id: 9, product_id: 13, serial_number: "CND143HVX1", model_number: "2540P", price: nil, firmware: "", photo: "0_pnzjgn5y", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00168", box_id: 9, product_id: 14, serial_number: "S1216806A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_ladb43qe", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00181", box_id: 9, product_id: 20, serial_number: "GE620-021USK1103000481", model_number: "MS-16G5", price: nil, firmware: "", photo: "0_3fyju9uq", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00330", box_id: 9, product_id: 13, serial_number: "CND02600GW", model_number: "2540P", price: nil, firmware: "", photo: "0_6uqx6eoz", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00393", box_id: 10, product_id: 21, serial_number: "VTP1123-25978", model_number: "515 XT", price: nil, firmware: "", photo: "0_614e8ann", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00164", box_id: 11, product_id: 22, serial_number: "NA2011190729445", model_number: "Tricaster 460", price: nil, firmware: "Tricaster Advanced Edition Software", photo: "0_2t9sgs02", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00010", box_id: 12, product_id: 23, serial_number: "CMVJ200CF4MD", model_number: "A1289", price: nil, firmware: "OSX Mavericks", photo: "0_jafsjxgs", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00009", box_id: 13, product_id: 23, serial_number: "H014701FEUH", model_number: "A1289", price: nil, firmware: "OSX Mavericks", photo: "0_fa8le6tq", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00203", box_id: 14, product_id: 23, serial_number: "C07L6007F4MF", model_number: "A1289", price: nil, firmware: "Windows 7", photo: "0_r08ezuje", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00397", box_id: 2, product_id: 24, serial_number: "4402031011", model_number: "e835", price: nil, firmware: "", photo: "0_gddwfc7o", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00398", box_id: 2, product_id: 24, serial_number: "4431023417", model_number: "e835", price: nil, firmware: "", photo: "0_dj3qdv2g", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00399", box_id: 2, product_id: 24, serial_number: "4431023421", model_number: "e835", price: nil, firmware: "", photo: "0_tkw5tp83", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00264", box_id: 2, product_id: 25, serial_number: "", model_number: "e815S", price: nil, firmware: "", photo: "0_8gq84w3y", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00265", box_id: 2, product_id: 25, serial_number: "", model_number: "e815S", price: nil, firmware: "", photo: "0_93z58ahs", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00267", box_id: 2, product_id: 26, serial_number: "4161009092", model_number: "SKP100G3", price: nil, firmware: "", photo: "0_boi7cwbw", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00400", box_id: 2, product_id: 27, serial_number: "", model_number: "A 2003 - UHF", price: nil, firmware: "", photo: "0_j7v4i17j", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00266", box_id: 2, product_id: 28, serial_number: "", model_number: "RE50B", price: nil, firmware: "", photo: "0_6fycln1g", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00401", box_id: 2, product_id: 27, serial_number: "", model_number: "A 2003 - UHF", price: nil, firmware: "", photo: "0_4lbymmw6", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00318", box_id: 2, product_id: 29, serial_number: "4053064683", model_number: "", price: nil, firmware: "", photo: "0_ygq2efoi", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00316", box_id: 2, product_id: 29, serial_number: "405306484", model_number: "", price: nil, firmware: "", photo: "0_7u9b27sf", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00329", box_id: 2, product_id: 29, serial_number: "4134083867", model_number: "", price: nil, firmware: "", photo: "0_5osjlpb1", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00317", box_id: 2, product_id: 29, serial_number: "4053064680", model_number: "", price: nil, firmware: "", photo: "0_yc3ucxcx", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00287", box_id: 2, product_id: 29, serial_number: "4103066573", model_number: "", price: nil, firmware: "", photo: "0_lkfbhbrk", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00328", box_id: 2, product_id: 29, serial_number: "4164085379", model_number: "", price: nil, firmware: "", photo: "0_2ylelapv", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00204", box_id: 2, product_id: 30, serial_number: "P218722", model_number: "ASA1", price: nil, firmware: "", photo: "0_b1qowuy4", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00046", box_id: 2, product_id: 31, serial_number: "AR5231", model_number: "ACCESS Rack", price: nil, firmware: "", photo: "0_xsu7bhkl", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00144", box_id: 15, product_id: 34, serial_number: "", model_number: "LEDTV1526", price: nil, firmware: "", photo: "0_w4hdz8l3", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00145", box_id: 15, product_id: 32, serial_number: "CBLMTF210388", model_number: "VE278", price: nil, firmware: "", photo: "0_3e3kx76r", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00149", box_id: 15, product_id: 35, serial_number: "ETLC3081371310C66F420A", model_number: "V223W", price: nil, firmware: "", photo: "0_xpfzh2d2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00192", box_id: 15, product_id: 35, serial_number: "ETLC3081372310A54C420A", model_number: "V223W", price: nil, firmware: "", photo: "0_2cwfp87m", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00152", box_id: 15, product_id: 32, serial_number: "D4LMQS034802", model_number: "VE228", price: nil, firmware: "", photo: "0_nglqhtu0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00148", box_id: 15, product_id: 32, serial_number: "BBLMTF072362", model_number: "VH236", price: nil, firmware: "", photo: "0_9zclso8o", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00146", box_id: 15, product_id: 32, serial_number: "CBLMTF210377", model_number: "VE278", price: nil, firmware: "", photo: "0_lcgv7bjp", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00403", box_id: 15, product_id: 35, serial_number: "ETLC3081371480CA1C420A", model_number: "V223W", price: nil, firmware: "", photo: "0_5llcc32r", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00151", box_id: 15, product_id: 32, serial_number: "D4LMQS034791", model_number: "VE228", price: nil, firmware: "", photo: "0_q4at9t5d", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00155", box_id: 15, product_id: 32, serial_number: "D4LMQS034787", model_number: "VE228", price: nil, firmware: "", photo: "0_06snqxdc", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00404", box_id: 15, product_id: 33, serial_number: "CNK9080HVR", model_number: "L2208w", price: nil, firmware: "", photo: "0_wl558r7p", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00191", box_id: 15, product_id: 32, serial_number: "D4LMQS034789", model_number: "VE228", price: nil, firmware: "", photo: "0_ylnsx69n", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00154", box_id: 15, product_id: 32, serial_number: "BBLMTF072373", model_number: "VH236", price: nil, firmware: "", photo: "0_1owikjp3", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00153", box_id: 15, product_id: 32, serial_number: "D4LMQS034786", model_number: "VE228", price: nil, firmware: "", photo: "0_9zcbnr41", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00150", box_id: 15, product_id: 32, serial_number: "D4LMQS034796", model_number: "VE228", price: nil, firmware: "", photo: "0_adk5lsnv", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00410", box_id: 16, product_id: 36, serial_number: "", model_number: "BD30AV", price: nil, firmware: "", photo: "0_0o60z0ve", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00411", box_id: 16, product_id: 36, serial_number: "BM22NC", model_number: "BD30AV", price: nil, firmware: "", photo: "0_47zee9sm", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00414", box_id: 16, product_id: 37, serial_number: "PSJ162305JN", model_number: "SF-10024 v2", price: nil, firmware: "", photo: "0_zwciy9e1", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00274", box_id: 16, product_id: 39, serial_number: "1207973", model_number: "Compact VideoHub 40", price: nil, firmware: "", photo: "0_5rbmym40", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00004", box_id: 16, product_id: 38, serial_number: "870276", model_number: "ATEM 2 M/E", price: nil, firmware: "", photo: "0_ff12ez9y", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00275", box_id: 16, product_id: 38, serial_number: "1198769", model_number: "ATEM 1 M/E", price: nil, firmware: "", photo: "0_vzu580td", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00408", box_id: 16, product_id: 40, serial_number: "N/A", model_number: "RA163", price: nil, firmware: "", photo: "0_nbbnw7f4", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00409", box_id: 16, product_id: 40, serial_number: "1213451", model_number: "RA163", price: nil, firmware: "", photo: "0_o4dsvx60", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00205", box_id: 17, product_id: 38, serial_number: "1197031", model_number: "ATEM TV Studio", price: nil, firmware: "", photo: "0_6ma8qcb2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00206", box_id: 17, product_id: 39, serial_number: "1417527", model_number: "Compact VideoHub 40", price: nil, firmware: "", photo: "0_zjtb7h0f", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00412", box_id: 17, product_id: 37, serial_number: "PSZ18451EYY", model_number: "SG102-24 v2", price: nil, firmware: "", photo: "0_2jv3k9ab", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00405", box_id: 17, product_id: 38, serial_number: "1670717", model_number: "ATEM Production Studio 4K", price: nil, firmware: "", photo: "0_d87n5qkb", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00406", box_id: 17, product_id: 41, serial_number: "06RC0463", model_number: "06RC0463", price: nil, firmware: "", photo: "0_rv054lq0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00407", box_id: 17, product_id: 41, serial_number: "31T05888", model_number: "DX-210", price: nil, firmware: "", photo: "0_ma6k0dby", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00417", box_id: nil, product_id: 10, serial_number: "2415098", model_number: "", price: nil, firmware: "", photo: "0_yvay77sp", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00418", box_id: nil, product_id: 12, serial_number: "2451159", model_number: "", price: nil, firmware: "", photo: "0_h7vn3n3a", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00420", box_id: 19, product_id: 10, serial_number: "2111082", model_number: "", price: nil, firmware: "", photo: "0_nip5fr53", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00342", box_id: 19, product_id: 10, serial_number: "1537944", model_number: "", price: nil, firmware: "", photo: "0_k4lfy90p", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00343", box_id: 19, product_id: 10, serial_number: "1654499", model_number: "", price: nil, firmware: "", photo: "0_axqfve4y", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00421", box_id: 19, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_86z3oct2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00156", box_id: 19, product_id: 12, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_6qmrxdsw", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00497", box_id: 19, product_id: 42, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_zmm2bjm0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00285", box_id: 19, product_id: 42, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_27pmifs9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00014", box_id: 19, product_id: 42, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: "0_pfacssd9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00039", box_id: 21, product_id: 43, serial_number: "739983", model_number: "", price: nil, firmware: "", photo: "0_fc6khohy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00284", box_id: 19, product_id: 43, serial_number: "1151544", model_number: "", price: nil, firmware: "", photo: "0_cfnhn1nc", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00036", box_id: 19, product_id: 44, serial_number: "852686", model_number: "", price: nil, firmware: "", photo: "0_2xkd8neg", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00278", box_id: 19, product_id: 44, serial_number: "1188104", model_number: "", price: nil, firmware: "", photo: "0_5fmaljub", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00037", box_id: 19, product_id: 44, serial_number: "632833", model_number: "", price: nil, firmware: "", photo: "0_y14a1qkw", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00277", box_id: 19, product_id: 44, serial_number: "1183893", model_number: "", price: nil, firmware: "", photo: "0_xe9que8x", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00035", box_id: 19, product_id: 44, serial_number: "851927", model_number: "", price: nil, firmware: "", photo: "0_yilo4cci", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00279", box_id: 19, product_id: 44, serial_number: "1183980", model_number: "", price: nil, firmware: "", photo: "0_cot9jbz9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00003", box_id: 19, product_id: 45, serial_number: "853255", model_number: "", price: nil, firmware: "", photo: "0_keotj9ey", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00002", box_id: 19, product_id: 45, serial_number: "854893", model_number: "", price: nil, firmware: "", photo: "0_gbm575v6", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00422", box_id: 19, product_id: 46, serial_number: "2056117", model_number: "", price: nil, firmware: "", photo: "0_ldloui5k", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00496", box_id: 19, product_id: 47, serial_number: "856958", model_number: "Mini Converter", price: nil, firmware: "", photo: "0_u4dg6sum", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00207", box_id: 19, product_id: 47, serial_number: "1167282", model_number: "Battery Converter", price: nil, firmware: "", photo: "0_x8gz69gy", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00030", box_id: 19, product_id: 48, serial_number: "602341", model_number: "USB 3.0", price: nil, firmware: "", photo: "0_vit67wue", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00029", box_id: 19, product_id: 48, serial_number: "N/A", model_number: "Thunderbolt", price: nil, firmware: "", photo: "0_m6ab7mvn", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00500", box_id: 19, product_id: 48, serial_number: "978029", model_number: "Thunderbolt", price: nil, firmware: "", photo: "0_m8jfwjnu", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00178", box_id: 19, product_id: 48, serial_number: "1346794", model_number: "Thunderbolt", price: nil, firmware: "", photo: "0_qfggfc7u", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00166", box_id: 19, product_id: 6, serial_number: "S1148603576", model_number: "Xenyx 502", price: nil, firmware: "", photo: "0_yz35a229", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00341", box_id: 19, product_id: 6, serial_number: "S1148703576", model_number: "Xenyx 502", price: nil, firmware: "", photo: "0_qo19jgfa", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00167", box_id: 19, product_id: 6, serial_number: "S1148635576", model_number: "Xenyx 502", price: nil, firmware: "", photo: "0_mx6os9b3", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00340", box_id: 19, product_id: 6, serial_number: "S1104209575", model_number: "Xenyx 802", price: nil, firmware: "", photo: "0_iizejz6t", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00359", box_id: 19, product_id: 6, serial_number: "S1209288575", model_number: "Xenyx 802", price: nil, firmware: "", photo: "0_t88dilad", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00423", box_id: 19, product_id: 6, serial_number: "S1424917575", model_number: "Xenyx 802", price: nil, firmware: "", photo: "0_f16liv9x", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00424", box_id: 19, product_id: 14, serial_number: "S1457426A31", model_number: "UCA202", price: nil, firmware: "", photo: "0_2g0ygylg", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00334", box_id: 19, product_id: 49, serial_number: "", model_number: "AUH0304F", price: nil, firmware: "", photo: "0_yh8odp9v", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00174", box_id: 19, product_id: 50, serial_number: "KFT31132", model_number: "", price: nil, firmware: "", photo: "0_txtbof96", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00338", box_id: 19, product_id: 51, serial_number: "K0167763", model_number: "Hi5-PLUS", price: nil, firmware: "", photo: "0_cdw3rmxl", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00346", box_id: 19, product_id: 52, serial_number: "K0075820", model_number: "HD10AMA", price: nil, firmware: "", photo: "0_gn9i7aik", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00313", box_id: 19, product_id: 52, serial_number: "K0061313", model_number: "HD10AMA", price: nil, firmware: "", photo: "0_0952eg4r", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00362", box_id: 19, product_id: 53, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_rtaqwio2", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00333", box_id: 19, product_id: 54, serial_number: "AX45B4AX4760", model_number: "", price: nil, firmware: "", photo: "0_fdmtxs0s", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00499", box_id: 19, product_id: 55, serial_number: "2162183606CEB", model_number: "GS108", price: nil, firmware: "", photo: "0_fny0udui", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00177", box_id: 19, product_id: 55, serial_number: "", model_number: "GS116", price: nil, firmware: "", photo: "0_vwbj02l8", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00336", box_id: 19, product_id: 56, serial_number: "NKS18310698", model_number: "RV042G", price: nil, firmware: "", photo: "0_bmo1p8y7", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00361", box_id: 19, product_id: 56, serial_number: "12N20609300673", model_number: "EA6500 V2", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00180", box_id: 21, product_id: 57, serial_number: "QBYZ1D6000668", model_number: "GO-SW-8GE", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00171", box_id: 19, product_id: 58, serial_number: "", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00172", box_id: 19, product_id: 59, serial_number: "10T10C17113164", model_number: "RE1000", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00175", box_id: 19, product_id: 60, serial_number: "241001133711801685", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00040", box_id: 20, product_id: 19, serial_number: "PG2B100646", model_number: "24.4.2", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00319", box_id: 20, product_id: 61, serial_number: "(21)IL02153", model_number: "MSP3", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00165", box_id: 19, product_id: 62, serial_number: "TAC72395", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00337", box_id: 19, product_id: 63, serial_number: "BP83629", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00320", box_id: 19, product_id: 64, serial_number: "2006.8039", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00426", box_id: 19, product_id: 65, serial_number: "", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00427", box_id: 21, product_id: 10, serial_number: "2163031", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00208", box_id: 21, product_id: 11, serial_number: "N/A", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00023", box_id: 21, product_id: 23, serial_number: "YM20608KEUF", model_number: "A1289", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00026", box_id: 21, product_id: 9, serial_number: "", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00430", box_id: 21, product_id: 67, serial_number: "", model_number: "", price: nil, firmware: "", photo: nil, responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00432", box_id: 22, product_id: 68, serial_number: "", model_number: "WH210", price: nil, firmware: "", photo: "0_vs0p0ah6", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00435", box_id: 22, product_id: 68, serial_number: "", model_number: "WH210", price: nil, firmware: "", photo: "0_1cwvlj16", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00434", box_id: 22, product_id: 68, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_y1bmproi", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00433", box_id: 22, product_id: 68, serial_number: "", model_number: "", price: nil, firmware: "", photo: "0_3qqb5aoe", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00323", box_id: 22, product_id: 69, serial_number: "C0213A0214", model_number: "RS-600", price: nil, firmware: "", photo: "0_dje2p9rk", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00305", box_id: 22, product_id: 69, serial_number: "C0213A0202", model_number: "RS-600", price: nil, firmware: "", photo: "0_jl663ze4", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00301", box_id: 22, product_id: 69, serial_number: "C0213A0203", model_number: "RS-600", price: nil, firmware: "", photo: "0_mm4un8ev", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00324", box_id: 22, product_id: 69, serial_number: "C0213A0219", model_number: "RS-600", price: nil, firmware: "", photo: "0_mi71o1fj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00306", box_id: 22, product_id: 69, serial_number: "C0213A0215", model_number: "RS-600", price: nil, firmware: "", photo: "0_yk1efmh9", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00303", box_id: 22, product_id: 69, serial_number: "C0213A0217", model_number: "RS-600", price: nil, firmware: "", photo: "0_yspaxls7", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00307", box_id: 22, product_id: 69, serial_number: "C0213A0211", model_number: "RS-600", price: nil, firmware: "", photo: "0_5nl6zs8r", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00325", box_id: 22, product_id: 69, serial_number: "C0213A0218", model_number: "RS-600", price: nil, firmware: "", photo: "0_ut08qcg5", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00304", box_id: 22, product_id: 69, serial_number: "C0213A0213", model_number: "RS-600", price: nil, firmware: "", photo: "0_m0yezjl0", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00322", box_id: 22, product_id: 69, serial_number: "C0213A0216", model_number: "RS-600", price: nil, firmware: "", photo: "0_leuagxuo", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00436", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_gp6hj74v", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00437", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_ci529if5", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00438", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_ck7ywv10", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00439", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_3z5lq1tl", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00440", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_33sihxx1", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00441", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_vi4fzuit", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00442", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_s73niq1y", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00455", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_wctaiwnj", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00443", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_wftc6ox3", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00444", box_id: 22, product_id: 70, serial_number: "", model_number: "CC-40", price: nil, firmware: "", photo: "0_oal2l01z", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00445", box_id: 22, product_id: 71, serial_number: "31T04830", model_number: "HME AC40", price: nil, firmware: "", photo: "0_1biwrz99", responsable: nil, location_id: nil, notes: nil, condition_id: nil},
  {barcode: "LNPS00454", box_id: 21, product_id: 46, serial_number: "2181853", model_number: "", price: nil, firmware: "", photo: "0_qpysf3x5", responsable: nil, location_id: nil, notes: nil, condition_id: nil}
])
Location.create!([
  {name: "NYC", country: "USA"},
  {name: "Miami", country: "USA"}
])
Movement.create!([
  {shipping_date: "2015-09-03", arrival_date: "2015-08-20", delivery_method: "Ground", is_return: false, return_id: nil, origin_id: 1, destination_id: 2}
])
Product.create!([
  {category_id: 4, name: "UPS Pro Series 1400VA 840W ", brand: "Xfinity"},
  {category_id: 6, name: "Samsung 46\" TV", brand: "Samsung"},
  {category_id: 6, name: "Samsung 40\" TV", brand: "Samsung"},
  {category_id: 4, name: "UPS 1350VA 810W", brand: "CyberPower"},
  {category_id: 4, name: "UPS Pro,650 Watts /1080 VA", brand: "APC"},
  {category_id: 1, name: "Xenyx Audio Mixer", brand: "Behringer"},
  {category_id: 5, name: "ProTalk XLS", brand: "Kenwood"},
  {category_id: 7, name: "Drill", brand: "Ryobi"},
  {category_id: 8, name: "MacBook Pro", brand: "Apple"},
  {category_id: 2, name: "UltraStudio Mini Recorder", brand: "BlackMagic Design"},
  {category_id: 2, name: "H.264 Pro Recorder", brand: "BlackMagic Design"},
  {category_id: 2, name: "DVI Extender", brand: "BlackMagic Design"},
  {category_id: 8, name: "EliteBook", brand: "HP"},
  {category_id: 1, name: "U-Control", brand: "Behringer"},
  {category_id: 2, name: "ikan Recorder", brand: "Ikan"},
  {category_id: 2, name: "ATEM 1 M/E Broadcast Panel", brand: "BlackMagic Design"},
  {category_id: 2, name: "Tally lights box", brand: "Pelican"},
  {category_id: 2, name: "Flolight", brand: "Flolight"},
  {category_id: 1, name: "StudioLive", brand: "Presonus"},
  {category_id: 8, name: "Notebook PC", brand: "MSI"},
  {category_id: 1, name: "JBL Speaker", brand: "JBL"},
  {category_id: 2, name: "Tricaster", brand: "NewTek"},
  {category_id: 8, name: "MacPro", brand: "Apple"},
  {category_id: 1, name: "Wireless handheld microphone", brand: "Sennheiser"},
  {category_id: 1, name: "Handheld microphone", brand: "Sennheiser"},
  {category_id: 1, name: "Wireless transmitter", brand: "Sennheiser"},
  {category_id: 1, name: "Antenna", brand: "Sennheiser"},
  {category_id: 1, name: "Handheld microphone EV", brand: "EV"},
  {category_id: 1, name: "Reciever EM 100G3", brand: "Sennheiser"},
  {category_id: 1, name: "Antenna splitter", brand: "Sennheiser"},
  {category_id: 1, name: "Comrex", brand: "Comrex"},
  {category_id: 6, name: "Monitor ASUS", brand: "ASUS"},
  {category_id: 6, name: "Monitor HP", brand: "HP"},
  {category_id: 6, name: "Monitor COBY", brand: "COBY"},
  {category_id: 6, name: "Monitor Acer", brand: "Acer"},
  {category_id: 2, name: "Delay device", brand: "B&M"},
  {category_id: 3, name: "Gigabit ethernet switch", brand: "CISCO"},
  {category_id: 2, name: "Video production switcher", brand: "BlackMagic Design"},
  {category_id: 2, name: "Video hub", brand: "BlackMagic Design"},
  {category_id: 1, name: "Audio distributor", brand: "Rolls"},
  {category_id: 5, name: "Intercom system", brand: "Clearcom"},
  {category_id: 2, name: "SDI Distribution", brand: "BlackMagic Design"},
  {category_id: 2, name: "SDI to Analog", brand: "BlackMagic Design"},
  {category_id: 2, name: "SDI to HDMI", brand: "BlackMagic Design"},
  {category_id: 2, name: "Analog to SDI", brand: "BlackMagic Design"},
  {category_id: 2, name: "SDI Distribution 4K", brand: "BlackMagic Design"},
  {category_id: 2, name: "HDMI to SDI", brand: "BlackMagic Design"},
  {category_id: 2, name: "Intensity Shuttle", brand: "BlackMagic Design"},
  {category_id: 8, name: "USB 3.0 Hub", brand: "Aluratek"},
  {category_id: 2, name: "DualHead2Go", brand: "Matrox"},
  {category_id: 2, name: "HD/SD to HDMI Converter", brand: "AJA"},
  {category_id: 2, name: "Embedder/Disembedder", brand: "AJA"},
  {category_id: 5, name: "Data Transfer Switch", brand: ""},
  {category_id: 2, name: "Game Capture HD", brand: "Elgato"},
  {category_id: 5, name: "ProSafe Gigabit Switch", brand: "Netgeat"},
  {category_id: 5, name: "Wireless router", brand: "CISCO"},
  {category_id: 5, name: "Gigabit switch", brand: "D-Link"},
  {category_id: 2, name: "HDMI Splitter", brand: ""},
  {category_id: 5, name: "WiFi Extender", brand: "CISCO"},
  {category_id: 2, name: "Dazzle", brand: "Pinnacle"},
  {category_id: 1, name: "Speaker", brand: "Yamaha"},
  {category_id: 2, name: "DVIPlus", brand: "Matrox"},
  {category_id: 2, name: "Monarch HD", brand: "Matrox"},
  {category_id: 1, name: "Instreamer 100", brand: "Barix"},
  {category_id: 2, name: "HDMI Switch", brand: ""},
  {category_id: 7, name: "Toolbox", brand: ""},
  {category_id: 1, name: "Microphones box", brand: ""},
  {category_id: 5, name: "Intercom Wireless Headset ", brand: "HME"},
  {category_id: 5, name: "Headset Base RS-602", brand: "Clear-Com"},
  {category_id: 5, name: "Clear-Com Headset CC-40", brand: "Clear-Com"},
  {category_id: 5, name: "BATTERY CHARGER", brand: "HME"}
])
User.create!([
  {name: "Gerardo Romero", email: "gerardo.romero@laureate.net", password_digest: "$2a$10$sFQAaL.0Ddg1z26gPacBAeLLk3yUL5AsBiE.mmEnPpPoWx5uVuwSq", remember_digest: nil, admin: true, reset_digest: nil, reset_sent_at: nil},
  {name: "Maximiliano Zampatti", email: "maximiliano.zampatti@laureate.net", password_digest: "$2a$10$pnSzLKIegwe0phEumUzHnOpP22aZPR5pmVDRI/2M/7W3hYgF0UPm.", remember_digest: nil, admin: true, reset_digest: "$2a$10$ZOigMSmP4UX8brk9EaF8DexFj0pNJa2FDf81L0rl1Ptt.zTleaW1.", reset_sent_at: "2015-08-12 17:24:46"},
  {name: "Luis Robles", email: "luis.robles@laureate.net", password_digest: "$2a$10$sUoNH3kEFTWYPQx2FYxLHeMC9K5EDvkJuzb054Rc.cB06RVKDYCB2", remember_digest: nil, admin: true, reset_digest: nil, reset_sent_at: nil},
  {name: "test", email: "mjzampa@gmail.com", password_digest: "$2a$10$8iObe0nK7V5UxJBohDNpw.2STGa8k21vS.wf7uQyrD4wjW6O8yoau", remember_digest: nil, admin: false, reset_digest: nil, reset_sent_at: nil}
])
